export type Currency = 'gbp' | 'usd' | 'eur' | 'jpy'
export type Condition = 'new' | 'used' | 'refurbished'
export type ListingType = 'physical' | 'digital'
export type PricingModel = 'fixed' | 'pwyw' | 'subscription' | 'auction'
export type DeliveryMethod = 'shipping' | 'pickup' | 'download'
export type Interval = 'monthly' | 'yearly'
export type ListingStatus =
  | 'draft'
  | 'active'
  | 'sold'
  | 'expired'
  | 'removed'
export type OrderStatus =
  | 'paid'
  | 'shipped'
  | 'delivered'
  | 'completed'
  | 'disputed'
  | 'refunded'
  | 'cancelled'
export type AuctionStatus =
  | 'scheduled'
  | 'active'
  | 'ended_sold'
  | 'ended_unsold'
  | 'payment_overdue'
  | 'cancelled'
export type BidStatus =
  | 'active'
  | 'outbid'
  | 'won'
  | 'lost'
  | 'purchased'
  | 'expired'
export type SubscriptionStatus = 'pending' | 'active' | 'paused' | 'past_due' | 'cancelled'
export type DisputeReason =
  | 'not_received'
  | 'not_as_described'
  | 'damaged'
  | 'unauthorised'
  | 'other'
export type ReportType = 'listing' | 'user'
