export type Currency = 'gbp' | 'usd' | 'eur'
export type Condition = 'new' | 'used' | 'refurbished'
export type ListingType = 'physical' | 'digital' | 'both'
export type PricingModel = 'fixed' | 'pwyw' | 'subscription' | 'auction'
export type DeliveryMethod = 'shipping' | 'pickup' | 'download'
export type Interval = 'monthly' | 'yearly'
export type ListingStatus =
  | 'draft'
  | 'active'
  | 'sold'
  | 'expired'
  | 'removed'
export type OrderStatus =
  | 'pending'
  | 'paid'
  | 'shipped'
  | 'delivered'
  | 'completed'
  | 'disputed'
  | 'refunded'
  | 'cancelled'
export type AuctionStatus =
  | 'scheduled'
  | 'active'
  | 'ended_sold'
  | 'ended_unsold'
  | 'cancelled'
export type BidStatus = 'active' | 'outbid' | 'won'
export type SubscriptionStatus = 'active' | 'paused' | 'cancelled'
export type DisputeReason =
  | 'not_received'
  | 'not_as_described'
  | 'damaged'
  | 'unauthorised'
  | 'other'
export type ReportType = 'listing' | 'user'
