export const APP_ROUTES = {
  HOME: '/',
  LISTINGS: {
    VIEW: (id: number): string => `/listings/${id}`,
    EDIT: (id: number): string => `/listings/${id}/edit`,
    MINE: '/listings',
  },
  CHECKOUT: (id: number): string => `/checkout/${id}`,
  PURCHASES: '/purchases',
  PURCHASE: (id: number): string => `/purchases/${id}`,
  SALES: '/sales',
  SALE: (id: number): string => `/sales/${id}`,
  BIDS: '/bids',
  SAVED: '/saved',
  SUBSCRIPTIONS: '/subscriptions',
  SUBSCRIBERS: '/subscribers',
  MESSAGES: '/messages',
  REVIEWS: '/reviews',
  ACCOUNT: '/account',
  SELLER_SETTINGS: '/account/seller',
  BECOME_SELLER: '/become-seller',
  PROFILE: (id: string): string => `/account/${id}`,
} as const
