/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedSubscribersRouteImport } from './routes/_authenticated/subscribers'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedBidsRouteImport } from './routes/_authenticated/bids'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AuthenticatedSalesOrderIdRouteImport } from './routes/_authenticated/sales.$orderId'
import { Route as AuthenticatedPurchasesOrderIdRouteImport } from './routes/_authenticated/purchases.$orderId'
import { Route as AuthenticatedMessagesThreadIdRouteImport } from './routes/_authenticated/messages.$threadId'
import { Route as AuthenticatedListingsMineRouteImport } from './routes/_authenticated/listings.mine'
import { Route as AuthenticatedListingsCreateRouteImport } from './routes/_authenticated/listings.create'
import { Route as AuthenticatedListingsListingIdRouteImport } from './routes/_authenticated/listings.$listingId'
import { Route as AuthenticatedCheckoutListingIdRouteImport } from './routes/_authenticated/checkout.$listingId'
import { Route as AuthenticatedAccountAccountIdRouteImport } from './routes/_authenticated/account.$accountId'
import { Route as AuthenticatedListingsListingIdEditRouteImport } from './routes/_authenticated/listings.$listingId_.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscribersRoute =
  AuthenticatedSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBidsRoute = AuthenticatedBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesOrderIdRoute =
  AuthenticatedSalesOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedSalesRoute,
  } as any)
const AuthenticatedPurchasesOrderIdRoute =
  AuthenticatedPurchasesOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)
const AuthenticatedMessagesThreadIdRoute =
  AuthenticatedMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedListingsMineRoute =
  AuthenticatedListingsMineRouteImport.update({
    id: '/listings/mine',
    path: '/listings/mine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsCreateRoute =
  AuthenticatedListingsCreateRouteImport.update({
    id: '/listings/create',
    path: '/listings/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsListingIdRoute =
  AuthenticatedListingsListingIdRouteImport.update({
    id: '/listings/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutListingIdRoute =
  AuthenticatedCheckoutListingIdRouteImport.update({
    id: '/checkout/$listingId',
    path: '/checkout/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountAccountIdRoute =
  AuthenticatedAccountAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedListingsListingIdEditRoute =
  AuthenticatedListingsListingIdEditRouteImport.update({
    id: '/listings/$listingId_/edit',
    path: '/listings/$listingId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/bids': typeof AuthenticatedBidsRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/search': typeof AuthenticatedSearchRoute
  '/seller': typeof AuthenticatedSellerRoute
  '/subscribers': typeof AuthenticatedSubscribersRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/$accountId': typeof AuthenticatedAccountAccountIdRoute
  '/checkout/$listingId': typeof AuthenticatedCheckoutListingIdRoute
  '/listings/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/listings/create': typeof AuthenticatedListingsCreateRoute
  '/listings/mine': typeof AuthenticatedListingsMineRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/purchases/$orderId': typeof AuthenticatedPurchasesOrderIdRoute
  '/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/listings/$listingId/edit': typeof AuthenticatedListingsListingIdEditRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/bids': typeof AuthenticatedBidsRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/search': typeof AuthenticatedSearchRoute
  '/seller': typeof AuthenticatedSellerRoute
  '/subscribers': typeof AuthenticatedSubscribersRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/$accountId': typeof AuthenticatedAccountAccountIdRoute
  '/checkout/$listingId': typeof AuthenticatedCheckoutListingIdRoute
  '/listings/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/listings/create': typeof AuthenticatedListingsCreateRoute
  '/listings/mine': typeof AuthenticatedListingsMineRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/purchases/$orderId': typeof AuthenticatedPurchasesOrderIdRoute
  '/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/listings/$listingId/edit': typeof AuthenticatedListingsListingIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/bids': typeof AuthenticatedBidsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/_authenticated/sales': typeof AuthenticatedSalesRouteWithChildren
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRoute
  '/_authenticated/subscribers': typeof AuthenticatedSubscribersRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/account/$accountId': typeof AuthenticatedAccountAccountIdRoute
  '/_authenticated/checkout/$listingId': typeof AuthenticatedCheckoutListingIdRoute
  '/_authenticated/listings/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/_authenticated/listings/create': typeof AuthenticatedListingsCreateRoute
  '/_authenticated/listings/mine': typeof AuthenticatedListingsMineRoute
  '/_authenticated/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/_authenticated/purchases/$orderId': typeof AuthenticatedPurchasesOrderIdRoute
  '/_authenticated/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/_authenticated/listings/$listingId_/edit': typeof AuthenticatedListingsListingIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/account'
    | '/bids'
    | '/messages'
    | '/purchases'
    | '/sales'
    | '/search'
    | '/seller'
    | '/subscribers'
    | '/subscriptions'
    | '/'
    | '/account/$accountId'
    | '/checkout/$listingId'
    | '/listings/$listingId'
    | '/listings/create'
    | '/listings/mine'
    | '/messages/$threadId'
    | '/purchases/$orderId'
    | '/sales/$orderId'
    | '/listings/$listingId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/account'
    | '/bids'
    | '/messages'
    | '/purchases'
    | '/sales'
    | '/search'
    | '/seller'
    | '/subscribers'
    | '/subscriptions'
    | '/'
    | '/account/$accountId'
    | '/checkout/$listingId'
    | '/listings/$listingId'
    | '/listings/create'
    | '/listings/mine'
    | '/messages/$threadId'
    | '/purchases/$orderId'
    | '/sales/$orderId'
    | '/listings/$listingId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/account'
    | '/_authenticated/bids'
    | '/_authenticated/messages'
    | '/_authenticated/purchases'
    | '/_authenticated/sales'
    | '/_authenticated/search'
    | '/_authenticated/seller'
    | '/_authenticated/subscribers'
    | '/_authenticated/subscriptions'
    | '/_authenticated/'
    | '/_authenticated/account/$accountId'
    | '/_authenticated/checkout/$listingId'
    | '/_authenticated/listings/$listingId'
    | '/_authenticated/listings/create'
    | '/_authenticated/listings/mine'
    | '/_authenticated/messages/$threadId'
    | '/_authenticated/purchases/$orderId'
    | '/_authenticated/sales/$orderId'
    | '/_authenticated/listings/$listingId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscribers': {
      id: '/_authenticated/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AuthenticatedSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bids': {
      id: '/_authenticated/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof AuthenticatedBidsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/$orderId': {
      id: '/_authenticated/sales/$orderId'
      path: '/$orderId'
      fullPath: '/sales/$orderId'
      preLoaderRoute: typeof AuthenticatedSalesOrderIdRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/purchases/$orderId': {
      id: '/_authenticated/purchases/$orderId'
      path: '/$orderId'
      fullPath: '/purchases/$orderId'
      preLoaderRoute: typeof AuthenticatedPurchasesOrderIdRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
    '/_authenticated/messages/$threadId': {
      id: '/_authenticated/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/listings/mine': {
      id: '/_authenticated/listings/mine'
      path: '/listings/mine'
      fullPath: '/listings/mine'
      preLoaderRoute: typeof AuthenticatedListingsMineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/create': {
      id: '/_authenticated/listings/create'
      path: '/listings/create'
      fullPath: '/listings/create'
      preLoaderRoute: typeof AuthenticatedListingsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/$listingId': {
      id: '/_authenticated/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof AuthenticatedListingsListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$listingId': {
      id: '/_authenticated/checkout/$listingId'
      path: '/checkout/$listingId'
      fullPath: '/checkout/$listingId'
      preLoaderRoute: typeof AuthenticatedCheckoutListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/$accountId': {
      id: '/_authenticated/account/$accountId'
      path: '/$accountId'
      fullPath: '/account/$accountId'
      preLoaderRoute: typeof AuthenticatedAccountAccountIdRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/listings/$listingId_/edit': {
      id: '/_authenticated/listings/$listingId_/edit'
      path: '/listings/$listingId/edit'
      fullPath: '/listings/$listingId/edit'
      preLoaderRoute: typeof AuthenticatedListingsListingIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAccountIdRoute: typeof AuthenticatedAccountAccountIdRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAccountIdRoute: AuthenticatedAccountAccountIdRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesThreadIdRoute: typeof AuthenticatedMessagesThreadIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesThreadIdRoute: AuthenticatedMessagesThreadIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedPurchasesRouteChildren {
  AuthenticatedPurchasesOrderIdRoute: typeof AuthenticatedPurchasesOrderIdRoute
}

const AuthenticatedPurchasesRouteChildren: AuthenticatedPurchasesRouteChildren =
  {
    AuthenticatedPurchasesOrderIdRoute: AuthenticatedPurchasesOrderIdRoute,
  }

const AuthenticatedPurchasesRouteWithChildren =
  AuthenticatedPurchasesRoute._addFileChildren(
    AuthenticatedPurchasesRouteChildren,
  )

interface AuthenticatedSalesRouteChildren {
  AuthenticatedSalesOrderIdRoute: typeof AuthenticatedSalesOrderIdRoute
}

const AuthenticatedSalesRouteChildren: AuthenticatedSalesRouteChildren = {
  AuthenticatedSalesOrderIdRoute: AuthenticatedSalesOrderIdRoute,
}

const AuthenticatedSalesRouteWithChildren =
  AuthenticatedSalesRoute._addFileChildren(AuthenticatedSalesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedBidsRoute: typeof AuthenticatedBidsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRouteWithChildren
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRouteWithChildren
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRoute
  AuthenticatedSubscribersRoute: typeof AuthenticatedSubscribersRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCheckoutListingIdRoute: typeof AuthenticatedCheckoutListingIdRoute
  AuthenticatedListingsListingIdRoute: typeof AuthenticatedListingsListingIdRoute
  AuthenticatedListingsCreateRoute: typeof AuthenticatedListingsCreateRoute
  AuthenticatedListingsMineRoute: typeof AuthenticatedListingsMineRoute
  AuthenticatedListingsListingIdEditRoute: typeof AuthenticatedListingsListingIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedBidsRoute: AuthenticatedBidsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRouteWithChildren,
  AuthenticatedSalesRoute: AuthenticatedSalesRouteWithChildren,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRoute,
  AuthenticatedSubscribersRoute: AuthenticatedSubscribersRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCheckoutListingIdRoute: AuthenticatedCheckoutListingIdRoute,
  AuthenticatedListingsListingIdRoute: AuthenticatedListingsListingIdRoute,
  AuthenticatedListingsCreateRoute: AuthenticatedListingsCreateRoute,
  AuthenticatedListingsMineRoute: AuthenticatedListingsMineRoute,
  AuthenticatedListingsListingIdEditRoute:
    AuthenticatedListingsListingIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
