/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedBecomeSellerRouteImport } from './routes/_authenticated/become-seller'
import { Route as AuthenticatedBidsRouteImport } from './routes/_authenticated/bids'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedSubscribersRouteImport } from './routes/_authenticated/subscribers'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedAccountAccountIdRouteImport } from './routes/_authenticated/account_.$accountId'
import { Route as AuthenticatedAccountSellerRouteImport } from './routes/_authenticated/account_.seller'
import { Route as AuthenticatedCheckoutListingIdRouteImport } from './routes/_authenticated/checkout.$listingId'
import { Route as AuthenticatedListingsListingIdRouteImport } from './routes/_authenticated/listings_.$listingId'
import { Route as AuthenticatedPurchasesOrderIdRouteImport } from './routes/_authenticated/purchases_.$orderId'
import { Route as AuthenticatedSalesOrderIdRouteImport } from './routes/_authenticated/sales_.$orderId'
import { Route as AuthenticatedListingsListingIdEditRouteImport } from './routes/_authenticated/listings_.$listingId_.edit'
import { Route as AuthenticatedListingsListingIdMessagesThreadIdRouteImport } from './routes/_authenticated/listings_.$listingId_.messages.$threadId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBecomeSellerRoute =
  AuthenticatedBecomeSellerRouteImport.update({
    id: '/become-seller',
    path: '/become-seller',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBidsRoute = AuthenticatedBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscribersRoute =
  AuthenticatedSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountAccountIdRoute =
  AuthenticatedAccountAccountIdRouteImport.update({
    id: '/account_/$accountId',
    path: '/account/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSellerRoute =
  AuthenticatedAccountSellerRouteImport.update({
    id: '/account_/seller',
    path: '/account/seller',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutListingIdRoute =
  AuthenticatedCheckoutListingIdRouteImport.update({
    id: '/checkout/$listingId',
    path: '/checkout/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsListingIdRoute =
  AuthenticatedListingsListingIdRouteImport.update({
    id: '/listings_/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesOrderIdRoute =
  AuthenticatedPurchasesOrderIdRouteImport.update({
    id: '/purchases_/$orderId',
    path: '/purchases/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrderIdRoute =
  AuthenticatedSalesOrderIdRouteImport.update({
    id: '/sales_/$orderId',
    path: '/sales/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsListingIdEditRoute =
  AuthenticatedListingsListingIdEditRouteImport.update({
    id: '/listings_/$listingId_/edit',
    path: '/listings/$listingId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsListingIdMessagesThreadIdRoute =
  AuthenticatedListingsListingIdMessagesThreadIdRouteImport.update({
    id: '/listings_/$listingId_/messages/$threadId',
    path: '/listings/$listingId/messages/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/account': typeof AuthenticatedAccountRoute
  '/become-seller': typeof AuthenticatedBecomeSellerRoute
  '/bids': typeof AuthenticatedBidsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/subscribers': typeof AuthenticatedSubscribersRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/account/$accountId': typeof AuthenticatedAccountAccountIdRoute
  '/account/seller': typeof AuthenticatedAccountSellerRoute
  '/checkout/$listingId': typeof AuthenticatedCheckoutListingIdRoute
  '/listings/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/purchases/$orderId': typeof AuthenticatedPurchasesOrderIdRoute
  '/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/listings/$listingId/edit': typeof AuthenticatedListingsListingIdEditRoute
  '/listings/$listingId/messages/$threadId': typeof AuthenticatedListingsListingIdMessagesThreadIdRoute
}
export interface FileRoutesByTo {
  '/account': typeof AuthenticatedAccountRoute
  '/become-seller': typeof AuthenticatedBecomeSellerRoute
  '/bids': typeof AuthenticatedBidsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/subscribers': typeof AuthenticatedSubscribersRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/$accountId': typeof AuthenticatedAccountAccountIdRoute
  '/account/seller': typeof AuthenticatedAccountSellerRoute
  '/checkout/$listingId': typeof AuthenticatedCheckoutListingIdRoute
  '/listings/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/purchases/$orderId': typeof AuthenticatedPurchasesOrderIdRoute
  '/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/listings/$listingId/edit': typeof AuthenticatedListingsListingIdEditRoute
  '/listings/$listingId/messages/$threadId': typeof AuthenticatedListingsListingIdMessagesThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/become-seller': typeof AuthenticatedBecomeSellerRoute
  '/_authenticated/bids': typeof AuthenticatedBidsRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/subscribers': typeof AuthenticatedSubscribersRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/account_/$accountId': typeof AuthenticatedAccountAccountIdRoute
  '/_authenticated/account_/seller': typeof AuthenticatedAccountSellerRoute
  '/_authenticated/checkout/$listingId': typeof AuthenticatedCheckoutListingIdRoute
  '/_authenticated/listings_/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/_authenticated/purchases_/$orderId': typeof AuthenticatedPurchasesOrderIdRoute
  '/_authenticated/sales_/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/_authenticated/listings_/$listingId_/edit': typeof AuthenticatedListingsListingIdEditRoute
  '/_authenticated/listings_/$listingId_/messages/$threadId': typeof AuthenticatedListingsListingIdMessagesThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/become-seller'
    | '/bids'
    | '/listings'
    | '/messages'
    | '/purchases'
    | '/reviews'
    | '/sales'
    | '/saved'
    | '/subscribers'
    | '/subscriptions'
    | '/account/$accountId'
    | '/account/seller'
    | '/checkout/$listingId'
    | '/listings/$listingId'
    | '/purchases/$orderId'
    | '/sales/$orderId'
    | '/listings/$listingId/edit'
    | '/listings/$listingId/messages/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/become-seller'
    | '/bids'
    | '/listings'
    | '/messages'
    | '/purchases'
    | '/reviews'
    | '/sales'
    | '/saved'
    | '/subscribers'
    | '/subscriptions'
    | '/'
    | '/account/$accountId'
    | '/account/seller'
    | '/checkout/$listingId'
    | '/listings/$listingId'
    | '/purchases/$orderId'
    | '/sales/$orderId'
    | '/listings/$listingId/edit'
    | '/listings/$listingId/messages/$threadId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/account'
    | '/_authenticated/become-seller'
    | '/_authenticated/bids'
    | '/_authenticated/listings'
    | '/_authenticated/messages'
    | '/_authenticated/purchases'
    | '/_authenticated/reviews'
    | '/_authenticated/sales'
    | '/_authenticated/saved'
    | '/_authenticated/subscribers'
    | '/_authenticated/subscriptions'
    | '/_authenticated/'
    | '/_authenticated/account_/$accountId'
    | '/_authenticated/account_/seller'
    | '/_authenticated/checkout/$listingId'
    | '/_authenticated/listings_/$listingId'
    | '/_authenticated/purchases_/$orderId'
    | '/_authenticated/sales_/$orderId'
    | '/_authenticated/listings_/$listingId_/edit'
    | '/_authenticated/listings_/$listingId_/messages/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/become-seller': {
      id: '/_authenticated/become-seller'
      path: '/become-seller'
      fullPath: '/become-seller'
      preLoaderRoute: typeof AuthenticatedBecomeSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bids': {
      id: '/_authenticated/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof AuthenticatedBidsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscribers': {
      id: '/_authenticated/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AuthenticatedSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account_/$accountId': {
      id: '/_authenticated/account_/$accountId'
      path: '/account/$accountId'
      fullPath: '/account/$accountId'
      preLoaderRoute: typeof AuthenticatedAccountAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account_/seller': {
      id: '/_authenticated/account_/seller'
      path: '/account/seller'
      fullPath: '/account/seller'
      preLoaderRoute: typeof AuthenticatedAccountSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$listingId': {
      id: '/_authenticated/checkout/$listingId'
      path: '/checkout/$listingId'
      fullPath: '/checkout/$listingId'
      preLoaderRoute: typeof AuthenticatedCheckoutListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings_/$listingId': {
      id: '/_authenticated/listings_/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof AuthenticatedListingsListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases_/$orderId': {
      id: '/_authenticated/purchases_/$orderId'
      path: '/purchases/$orderId'
      fullPath: '/purchases/$orderId'
      preLoaderRoute: typeof AuthenticatedPurchasesOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales_/$orderId': {
      id: '/_authenticated/sales_/$orderId'
      path: '/sales/$orderId'
      fullPath: '/sales/$orderId'
      preLoaderRoute: typeof AuthenticatedSalesOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings_/$listingId_/edit': {
      id: '/_authenticated/listings_/$listingId_/edit'
      path: '/listings/$listingId/edit'
      fullPath: '/listings/$listingId/edit'
      preLoaderRoute: typeof AuthenticatedListingsListingIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings_/$listingId_/messages/$threadId': {
      id: '/_authenticated/listings_/$listingId_/messages/$threadId'
      path: '/listings/$listingId/messages/$threadId'
      fullPath: '/listings/$listingId/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedListingsListingIdMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBecomeSellerRoute: typeof AuthenticatedBecomeSellerRoute
  AuthenticatedBidsRoute: typeof AuthenticatedBidsRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSubscribersRoute: typeof AuthenticatedSubscribersRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountAccountIdRoute: typeof AuthenticatedAccountAccountIdRoute
  AuthenticatedAccountSellerRoute: typeof AuthenticatedAccountSellerRoute
  AuthenticatedCheckoutListingIdRoute: typeof AuthenticatedCheckoutListingIdRoute
  AuthenticatedListingsListingIdRoute: typeof AuthenticatedListingsListingIdRoute
  AuthenticatedPurchasesOrderIdRoute: typeof AuthenticatedPurchasesOrderIdRoute
  AuthenticatedSalesOrderIdRoute: typeof AuthenticatedSalesOrderIdRoute
  AuthenticatedListingsListingIdEditRoute: typeof AuthenticatedListingsListingIdEditRoute
  AuthenticatedListingsListingIdMessagesThreadIdRoute: typeof AuthenticatedListingsListingIdMessagesThreadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBecomeSellerRoute: AuthenticatedBecomeSellerRoute,
  AuthenticatedBidsRoute: AuthenticatedBidsRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSubscribersRoute: AuthenticatedSubscribersRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountAccountIdRoute: AuthenticatedAccountAccountIdRoute,
  AuthenticatedAccountSellerRoute: AuthenticatedAccountSellerRoute,
  AuthenticatedCheckoutListingIdRoute: AuthenticatedCheckoutListingIdRoute,
  AuthenticatedListingsListingIdRoute: AuthenticatedListingsListingIdRoute,
  AuthenticatedPurchasesOrderIdRoute: AuthenticatedPurchasesOrderIdRoute,
  AuthenticatedSalesOrderIdRoute: AuthenticatedSalesOrderIdRoute,
  AuthenticatedListingsListingIdEditRoute:
    AuthenticatedListingsListingIdEditRoute,
  AuthenticatedListingsListingIdMessagesThreadIdRoute:
    AuthenticatedListingsListingIdMessagesThreadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
